### ISSUE TITLE
EC2에 배포 및 CI/CD 적용

### ISSUE THREAD

**Issue by mdgarden** [mdgarden/fastcampus-sns#2]
## 목표
강좌에서는 Heroku를 사용하였으나 Heroku가 유료화된 관계로 EC2에 서버 올리고 CI/CD 통합해보는걸로 해보려함.
- 목표 : 깃허브 리포지토리 main 브랜치에 새로운 변경이 발생하면, EC2에 자동으로 푸쉬 및 배포 됨

## 태스크
- [x] AWS 신규 계정 작성 및 가입
- [x] EC2에 배포
- [x] CI/CD 적용

## 참고 자료

[# GitHub Actions, AWS CodeDeploy 를 활용한 CI/CD 적용](https://velog.io/@cataiden/ci-cd-with-github-actions-and-aws-codedeploy)
[Complete CI/CD with AWS CodeCommit, AWS CodeBuild, AWS CodeDeploy, and AWS CodePipeline](https://aws.amazon.com/ko/blogs/devops/complete-ci-cd-with-aws-codecommit-aws-codebuild-aws-codedeploy-and-aws-codepipeline/)
[Spring BootアプリのAWS環境へのCI/CD環境構築の第一歩](https://zenn.dev/ryo7/articles/first-step-to-spring-boot-cicd)

**Comment by mdgarden** [comment]
## EC2 배포
filezilar? 쓰지 않고 인텔리제이로 바로 배포
원격 주소는 `/opt/app/build/libs/sns-0.0.1-SNAPSHOT.jar`

[여기 참고 많이 함](https://velog.io/@dohaeng0/AWS%EC%97%90-Spring-Boot-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EB%B0%B0%ED%8F%AC-2-EC2-%EC%84%B8%ED%8C%85%EF%BC%86%EB%B0%B0%ED%8F%AC-%EB%8F%84%EB%A9%94%EC%9D%B8-%EC%97%B0%EA%B2%B0)

**Comment by mdgarden** [comment]
스프링부트 프로젝트를 CI/CD 자동화하는 방법

Q. jar파일은 코드가 아닌데 어떻게 코드의 지속적인 통합과 관리가 가능한지?

A. 천재피티)

AWS CodeDeploy를 사용하여 Spring Boot 애플리케이션(`.jar` 파일)의 CI/CD를 구성하는 과정은 몇 단계로 나눌 수 있습니다. 이 과정은 소스 코드 저장소에서 변경 사항을 감지하고, 빌드 및 테스트를 자동화한 후, AWS CodeDeploy를 통해 변경 사항을 EC2 인스턴스나 AWS Elastic Beanstalk과 같은 서비스에 자동으로 배포하는 것을 포함합니다. 여기서는 GitHub와 AWS CodeBuild, AWS CodeDeploy를 사용한 일반적인 워크플로우를 소개합니다.

### 1. 소스 코드 및 빌드 스펙 준비

- GitHub에 Spring Boot 애플리케이션의 소스 코드를 저장합니다.
- 프로젝트 루트에 `buildspec.yml` 파일을 생성하여 AWS CodeBuild에서 사용할 빌드 명령어를 정의합니다. 예시는 다음과 같습니다:

```yaml
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Installing source dependencies...
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/*.jar
```

### 2. AWS CodeBuild 프로젝트 생성

- AWS Management Console에서 AWS CodeBuild로 이동하여 새 빌드 프로젝트를 생성합니다.
- 소스 공급자(Source Provider)로 GitHub를 선택하고, 레포지토리를 연결합니다.
- 빌드 환경을 구성하고, `buildspec.yml` 파일을 사용하도록 설정합니다.
- 빌드 프로젝트가 `.jar` 파일을 생성하도록 구성합니다.

> CodeBuild에 웹훅 설정이 있었다. main 브랜치에 대한 풀리퀘스트가 merge 될 때마다 빌드를 실행하도록 구성할 수 있다. 웹훅의 필터 그룹을 추가하고, 이벤트 유형은 "PULL_REQUEST_MERGED", 빌드 시작 필터는 유형- HEAD_REF 패턴- refs/head/main 으로 입력

### 3. AWS CodeDeploy 설정

- AWS CodeDeploy 애플리케이션과 배포 그룹을 생성합니다.
- EC2 인스턴스에 CodeDeploy 에이전트를 설치합니다.
- `appspec.yml` 파일을 프로젝트 루트에 생성하고 배포 스펙을 정의합니다. 이 파일은 배포할 파일과 배포 시 실행할 후크 스크립트를 지정합니다. 예시는 다음과 같습니다:

```yaml
version: 0.0
os: linux
files:
  - source: /
    destination: /opt/app
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
```

- `scripts/start.sh` 스크립트에는 `.jar` 파일을 실행하는 명령어가 포함되어야 합니다.

### 4. AWS CodePipeline 생성

- AWS CodePipeline을 사용하여 소스 코드의 변경 사항을 자동으로 감지하고 AWS CodeBuild 및 AWS CodeDeploy와 연결합니다.
- 새 파이프라인을 생성하고, 소스 스테이지로 GitHub 레포지토리를 선택합니다.
- 빌드 스테이지에서 앞서 생성한 AWS CodeBuild 프로젝트를 선택합니다.
- 배포 스테이지에서 AWS CodeDeploy 애플리케이션과 배포 그룹을 선택합니다.

이 과정을 통해 소스 코드의 변경 사항이 GitHub에 푸시될 때마다 AWS CodePipeline이 자동으로 트리거되어 코드를 빌드하고, 생성된 `.jar` 파일을 AWS CodeDeploy를 통해 EC2 인스턴스나 Elastic Beanstalk 애플리케이션에 배포합니다. CI/CD 파이프라인을 성공적으로 구성하면, 개발 팀은 소프트웨어 배포 과정을 자동화하고 효율성을 높일 수 있습니다.
